# Generated by Django 4.2.13 on 2025-04-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasLakersBis', '0005_alter_sucursaleslakers_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursaleslakers',
            name='retiro_expres',
            field=models.BooleanField(blank=True, db_column='RETIRO_EXPRES', default=False, null=True),
        ),
    ]
