# Generated by Django 4.2.13 on 2025-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasLakersBis', '0006_sucursaleslakers_retiro_expres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursaleslakers',
            name='retiro_expres',
            field=models.BooleanField(blank=True, db_column='RETIRO_EXPRES', null=True),
        ),
    ]
