# Generated by Django 3.2.6 on 2026-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasLakersBis', '0007_alter_sucursaleslakers_retiro_expres'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursaleslakers',
            name='mail_grupo_emp',
            field=models.CharField(blank=True, db_column='MAIL_GRUP_EMP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sucursaleslakers',
            name='llave_prueba',
            field=models.BinaryField(blank=True, db_column='NRO_SUC_ACTUAL', max_length='max', null=True),
        ),
    ]
