# Generated by Django 3.2.6 on 2026-07-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultasLakersBis', '0008_auto_20260511_0929'),
        ('consultasLakersBis', '0008_sucursaleslakers_mail_grupo_emp_and_more'),
        ('consultasLakersBis', '0009_alter_sucursaleslakers_dias_default'),
    ]

    operations = [
    ]
