# Generated by Django 4.2.13 on 2025-11-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0012_eb_facturamanual_fechavencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoReserva',
            fields=[
                ('id_turno_reserva', models.AutoField(db_column='id_turno_reserva', primary_key=True, serialize=False)),
                ('codigo_proveedor', models.CharField(max_length=6, verbose_name='Código Proveedor')),
                ('nombre_proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Proveedor')),
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('orden_compra', models.CharField(max_length=14, verbose_name='Orden de Compra')),
                ('remitos', models.CharField(max_length=100, verbose_name='Remitos')),
                ('cantidad_unidades', models.IntegerField(verbose_name='Cantidad de Unidades')),
                ('cantidad_bultos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Bultos')),
                ('observaciones', models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones')),
                ('usuario_creador', models.CharField(max_length=150, verbose_name='Usuario que Creó el Turno')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Turno Reserva',
                'verbose_name_plural': 'Turnos Reservas',
                'db_table': 'TurnoReserva',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('fecha', 'hora_inicio')},
            },
        ),
    ]
