# Generated by Django 4.2.13 on 2025-11-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0013_turnoreserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTurno',
            fields=[
                ('id_estado', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Estado')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('orden_ejecucion', models.IntegerField(unique=True, verbose_name='Orden de Ejecución')),
                ('es_requerido', models.BooleanField(default=True, verbose_name='¿Es Requerido?')),
                ('color', models.CharField(default='#17a2b8', max_length=7, verbose_name='Color (Hex)')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Estado de Turno',
                'verbose_name_plural': 'Estados de Turnos',
                'db_table': 'EstadoTurno',
                'ordering': ['orden_ejecucion'],
            },
        ),
        migrations.AddField(
            model_name='turnoreserva',
            name='estado_actual_desde',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estado Actual Desde'),
        ),
        migrations.AddField(
            model_name='turnoreserva',
            name='usuario_ultima_modificacion_estado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario Última Modificación Estado'),
        ),
        migrations.CreateModel(
            name='HistorialEstadoTurno',
            fields=[
                ('id_historial', models.AutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuario que Realizó el Cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Cambio')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='id_estado_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_anterior', to='consultasTango.estadoturno', verbose_name='Estado Anterior')),
                ('estado_nuevo', models.ForeignKey(db_column='id_estado_nuevo', on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_nuevo', to='consultasTango.estadoturno', verbose_name='Estado Nuevo')),
                ('turno', models.ForeignKey(db_column='id_turno_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='consultasTango.turnoreserva', verbose_name='Turno Reserva')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estados',
                'db_table': 'HistorialEstadoTurno',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AlterField(
            model_name='turnoreserva',
            name='estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='consultasTango.estadoturno', verbose_name='Estado del Turno'),
        ),
    ]
