# Generated by Django 4.2.13 on 2025-11-27 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0014_estadoturno_turnoreserva_estado_actual_desde_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigoserror',
            options={'ordering': ['Categoria', 'CodigoError'], 'verbose_name': 'Código de Error', 'verbose_name_plural': 'Códigos de Error'},
        ),
        # migrations.AlterField(
        #     model_name='codigoserror',
        #     name='Activo',
        #     field=models.BooleanField(default=True, verbose_name='Activo'),
        # ),
        migrations.AddField(
            model_name='codigoserror',
            name='Categoria',
            field=models.CharField(choices=[('DOCUMENTACION', 'Documentación'), ('MERCADERIA', 'Mercadería'), ('EMBALAJE', 'Embalaje'), ('CANTIDAD', 'Cantidad'), ('CALIDAD', 'Calidad'), ('ETIQUETADO', 'Etiquetado'), ('OTROS', 'Otros')], default='OTROS', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='codigoserror',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 27, 18, 41, 6, 255206, tzinfo=datetime.timezone.utc), verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigoserror',
            name='FechaModificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='estadoturno',
            name='permite_editar',
            field=models.BooleanField(default=True, verbose_name='¿Permite Editar Turno?'),
        ),
        migrations.AlterField(
            model_name='codigoserror',
            name='CodigoError',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='codigoserror',
            name='DescripcionError',
            field=models.CharField(max_length=200, verbose_name='Descripción del Error'),
        ),
        migrations.AlterModelTable(
            name='codigoserror',
            table='CodigosError',
        ),
        migrations.CreateModel(
            name='IncidenciasTurno',
            fields=[
                ('id_incidencia', models.AutoField(db_column='id_incidencia', primary_key=True, serialize=False)),
                ('cantidad_afectada', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Afectada')),
                ('detalle', models.TextField(blank=True, max_length=500, null=True, verbose_name='Detalle de la Incidencia')),
                ('usuario_registro', models.CharField(max_length=150, verbose_name='Usuario que Registró')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Registro')),
                ('resuelto', models.BooleanField(default=False, verbose_name='¿Resuelto?')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Resolución')),
                ('usuario_resolucion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario Resolución')),
                ('observaciones_resolucion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones Resolución')),
                ('codigo_error', models.ForeignKey(db_column='CodigoError', on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='consultasTango.codigoserror', verbose_name='Código de Error')),
                ('turno', models.ForeignKey(db_column='id_turno_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='consultasTango.turnoreserva', verbose_name='Turno Reserva')),
            ],
            options={
                'verbose_name': 'Incidencia de Turno',
                'verbose_name_plural': 'Incidencias de Turnos',
                'db_table': 'IncidenciasTurno',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
