# Generated by Django 4.2.13 on 2025-11-27 18:41
# FIXED: This migration originally had operations on fields/tables that already exist in the database
# Now kept empty to allow subsequent migrations to apply cleanly

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0014_estadoturno_turnoreserva_estado_actual_desde_and_more'),
    ]

    operations = [
        # All original operations have been removed because the corresponding
        # database objects already exist in mi_db_2 (SQL Server Tango database)
        # - CodigosError table with Categoria, FechaCreacion, FechaModificacion fields
        # - EstadoTurno table with permite_editar field
        # - IncidenciasTurno table
    ]
