# Generated by Django 4.2.13 on 2025-12-01 16:44

import consultasTango.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0016_alter_turnoreserva_orden_compra'),
    ]

    operations = [
        # Las siguientes operaciones de CodigosError y EstadoTurno ya existen en la DB
        # Se comentan para evitar errores de columnas duplicadas
        # migrations.AlterModelOptions(
        #     name='codigoserror',
        #     options={'ordering': ['Categoria', 'CodigoError'], 'verbose_name': 'Código de Error', 'verbose_name_plural': 'Códigos de Error'},
        # ),
        # migrations.AddField(
        #     model_name='codigoserror',
        #     name='Activo',
        #     field=models.BooleanField(default=True, verbose_name='Activo'),
        # ),
        # migrations.AddField(
        #     model_name='codigoserror',
        #     name='Categoria',
        #     field=models.CharField(choices=[('DOCUMENTACION', 'Documentación'), ('MERCADERIA', 'Mercadería'), ('EMBALAJE', 'Embalaje'), ('CANTIDAD', 'Cantidad'), ('CALIDAD', 'Calidad'), ('ETIQUETADO', 'Etiquetado'), ('OTROS', 'Otros')], default='OTROS', max_length=50, verbose_name='Categoría'),
        # ),
        # migrations.AddField(
        #     model_name='codigoserror',
        #     name='FechaCreacion',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='codigoserror',
        #     name='FechaModificacion',
        #     field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        # ),
        # migrations.AddField(
        #     model_name='estadoturno',
        #     name='permite_editar',
        #     field=models.BooleanField(default=True, verbose_name='¿Permite Editar Turno?'),
        # ),
        # migrations.AlterField(
        #     model_name='codigoserror',
        #     name='CodigoError',
        #     field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código'),
        # ),
        # migrations.AlterField(
        #     model_name='codigoserror',
        #     name='DescripcionError',
        #     field=models.CharField(max_length=200, verbose_name='Descripción del Error'),
        # ),
        # migrations.AlterModelTable(
        #     name='codigoserror',
        #     table='CodigosError',
        # ),
        # migrations.CreateModel(
        #     name='IncidenciasTurno',
        #     ... ya existe
        # ),
        
        # Solo crear la tabla AdjuntoTurnoReserva (nueva)
        migrations.CreateModel(
            name='AdjuntoTurnoReserva',
            fields=[
                ('id_adjunto', models.AutoField(db_column='id_adjunto', primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=consultasTango.models.ruta_adjunto_turno, validators=[consultasTango.models.validar_extension_adjunto], verbose_name='Archivo')),
                ('tipo_documento', models.CharField(choices=[('REMITO', 'Remito'), ('CONSOLIDADO', 'Detalle Consolidado de Carga'), ('FACTURA', 'Factura'), ('OTRO', 'Otro Documento')], default='OTRO', max_length=20, verbose_name='Tipo de Documento')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('tipo_archivo', models.CharField(max_length=100, verbose_name='Tipo MIME del Archivo')),
                ('tamaño_bytes', models.PositiveIntegerField(verbose_name='Tamaño en Bytes')),
                ('usuario_subio', models.CharField(max_length=150, verbose_name='Usuario que Subió el Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('turno', models.ForeignKey(db_column='id_turno_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='consultasTango.turnoreserva', verbose_name='Turno Reserva')),
            ],
            options={
                'verbose_name': 'Adjunto de Turno',
                'verbose_name_plural': 'Adjuntos de Turnos',
                'db_table': 'AdjuntoTurnoReserva',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
